var dir_b963901bde9403adf4e823a420f4fcbe =
[
    [ "AdditiveDefinition.cs", "_additive_definition_8cs.html", "_additive_definition_8cs" ],
    [ "BuildableItemDefinition.cs", "_buildable_item_definition_8cs.html", "_buildable_item_definition_8cs" ],
    [ "CashDefinition.cs", "_cash_definition_8cs.html", "_cash_definition_8cs" ],
    [ "CashInstance.cs", "_cash_instance_8cs.html", "_cash_instance_8cs" ],
    [ "CashPickup.cs", "_cash_pickup_8cs.html", "_cash_pickup_8cs" ],
    [ "ClipboardSlot.cs", "_clipboard_slot_8cs.html", "_clipboard_slot_8cs" ],
    [ "EItemCategory.cs", "_e_item_category_8cs.html", "_e_item_category_8cs" ],
    [ "ELegalStatus.cs", "_e_legal_status_8cs.html", "_e_legal_status_8cs" ],
    [ "EQuality.cs", "_e_quality_8cs.html", "_e_quality_8cs" ],
    [ "IDs.cs", "_i_ds_8cs.html", "_i_ds_8cs" ],
    [ "IItemSlotOwner.cs", "_i_item_slot_owner_8cs.html", "_i_item_slot_owner_8cs" ],
    [ "IntegerItemDefinition.cs", "_integer_item_definition_8cs.html", "_integer_item_definition_8cs" ],
    [ "IntegerItemInstance.cs", "_integer_item_instance_8cs.html", "_integer_item_instance_8cs" ],
    [ "ItemDefinition.cs", "_item_definition_8cs.html", "_item_definition_8cs" ],
    [ "ItemFilter.cs", "_item_filter_8cs.html", "_item_filter_8cs" ],
    [ "ItemFilter_Category.cs", "_item_filter___category_8cs.html", "_item_filter___category_8cs" ],
    [ "ItemFilter_ClothingSlot.cs", "_item_filter___clothing_slot_8cs.html", "_item_filter___clothing_slot_8cs" ],
    [ "ItemFilter_Dryable.cs", "_item_filter___dryable_8cs.html", "_item_filter___dryable_8cs" ],
    [ "ItemFilter_ID.cs", "_item_filter___i_d_8cs.html", "_item_filter___i_d_8cs" ],
    [ "ItemFilter_MixingIngredient.cs", "_item_filter___mixing_ingredient_8cs.html", "_item_filter___mixing_ingredient_8cs" ],
    [ "ItemFilter_PackagedProduct.cs", "_item_filter___packaged_product_8cs.html", "_item_filter___packaged_product_8cs" ],
    [ "ItemFilter_UnpackagedProduct.cs", "_item_filter___unpackaged_product_8cs.html", "_item_filter___unpackaged_product_8cs" ],
    [ "ItemGiver.cs", "_item_giver_8cs.html", "_item_giver_8cs" ],
    [ "ItemInstance.cs", "_item_instance_8cs.html", "_item_instance_8cs" ],
    [ "ItemPickup.cs", "_item_pickup_8cs.html", "_item_pickup_8cs" ],
    [ "ItemQuality.cs", "_item_quality_8cs.html", "_item_quality_8cs" ],
    [ "ItemRemover.cs", "_item_remover_8cs.html", "_item_remover_8cs" ],
    [ "ItemSerializers.cs", "_item_serializers_8cs.html", "_item_serializers_8cs" ],
    [ "ItemSlot.cs", "_item_slot_8cs.html", "_item_slot_8cs" ],
    [ "ItemSlotLock.cs", "_item_slot_lock_8cs.html", "_item_slot_lock_8cs" ],
    [ "QualityItemDefinition.cs", "_quality_item_definition_8cs.html", "_quality_item_definition_8cs" ],
    [ "QualityItemInstance.cs", "_quality_item_instance_8cs.html", "_quality_item_instance_8cs" ],
    [ "SoilDefinition.cs", "_soil_definition_8cs.html", "_soil_definition_8cs" ],
    [ "StorableItemDefinition.cs", "_storable_item_definition_8cs.html", "_storable_item_definition_8cs" ]
];