var dir_1bbb999c0f45fb13ab397580a92cb706 =
[
    [ "Assault.cs", "_assault_8cs.html", "_assault_8cs" ],
    [ "AttemptingToSell.cs", "_attempting_to_sell_8cs.html", "_attempting_to_sell_8cs" ],
    [ "BrandishingWeapon.cs", "_brandishing_weapon_8cs.html", "_brandishing_weapon_8cs" ],
    [ "CheckpointInstance.cs", "_checkpoint_instance_8cs.html", "_checkpoint_instance_8cs" ],
    [ "CheckpointManager.cs", "_checkpoint_manager_8cs.html", "_checkpoint_manager_8cs" ],
    [ "Crime.cs", "_crime_8cs.html", "_crime_8cs" ],
    [ "CurfewInstance.cs", "_curfew_instance_8cs.html", "_curfew_instance_8cs" ],
    [ "CurfewManager.cs", "_curfew_manager_8cs.html", "_curfew_manager_8cs" ],
    [ "DeadlyAssault.cs", "_deadly_assault_8cs.html", "_deadly_assault_8cs" ],
    [ "DischargeFirearm.cs", "_discharge_firearm_8cs.html", "_discharge_firearm_8cs" ],
    [ "DrugTrafficking.cs", "_drug_trafficking_8cs.html", "_drug_trafficking_8cs" ],
    [ "Evading.cs", "_evading_8cs.html", "_evading_8cs" ],
    [ "FailureToComply.cs", "_failure_to_comply_8cs.html", "_failure_to_comply_8cs" ],
    [ "LawActivitySettings.cs", "_law_activity_settings_8cs.html", "_law_activity_settings_8cs" ],
    [ "LawController.cs", "_law_controller_8cs.html", "_law_controller_8cs" ],
    [ "LawManager.cs", "_law_manager_8cs.html", "_law_manager_8cs" ],
    [ "PatrolInstance.cs", "_patrol_instance_8cs.html", "_patrol_instance_8cs" ],
    [ "PenaltyHandler.cs", "_penalty_handler_8cs.html", "_penalty_handler_8cs" ],
    [ "PossessingControlledSubstances.cs", "_possessing_controlled_substances_8cs.html", "_possessing_controlled_substances_8cs" ],
    [ "PossessingHighSeverityDrug.cs", "_possessing_high_severity_drug_8cs.html", "_possessing_high_severity_drug_8cs" ],
    [ "PossessingLowSeverityDrug.cs", "_possessing_low_severity_drug_8cs.html", "_possessing_low_severity_drug_8cs" ],
    [ "PossessingModerateSeverityDrug.cs", "_possessing_moderate_severity_drug_8cs.html", "_possessing_moderate_severity_drug_8cs" ],
    [ "SentryInstance.cs", "_sentry_instance_8cs.html", "_sentry_instance_8cs" ],
    [ "SentryLocation.cs", "_sentry_location_8cs.html", "_sentry_location_8cs" ],
    [ "Theft.cs", "_theft_8cs.html", "_theft_8cs" ],
    [ "TransportingIllicitItems.cs", "_transporting_illicit_items_8cs.html", "_transporting_illicit_items_8cs" ],
    [ "Vandalism.cs", "_vandalism_8cs.html", "_vandalism_8cs" ],
    [ "VehiclePatrolInstance.cs", "_vehicle_patrol_instance_8cs.html", "_vehicle_patrol_instance_8cs" ],
    [ "VehicularAssault.cs", "_vehicular_assault_8cs.html", "_vehicular_assault_8cs" ],
    [ "ViolatingCurfew.cs", "_violating_curfew_8cs.html", "_violating_curfew_8cs" ]
];